# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 920)
        MainWindow.setMaximumSize(QtCore.QSize(1800, 920))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graficas = QtWidgets.QWidget(self.centralwidget)
        self.graficas.setGeometry(QtCore.QRect(0, 0, 1801, 611))
        self.graficas.setObjectName("graficas")
        self.empezar_boton = QtWidgets.QPushButton(self.centralwidget)
        self.empezar_boton.setGeometry(QtCore.QRect(1570, 630, 211, 51))
        self.empezar_boton.setCheckable(False)
        self.empezar_boton.setObjectName("empezar_boton")
        self.terminar_boton = QtWidgets.QPushButton(self.centralwidget)
        self.terminar_boton.setGeometry(QtCore.QRect(1570, 690, 211, 51))
        self.terminar_boton.setObjectName("terminar_boton")
        self.datos_raw = QtWidgets.QLabel(self.centralwidget)
        self.datos_raw.setGeometry(QtCore.QRect(10, 640, 531, 251))
        self.datos_raw.setText("")
        self.datos_raw.setObjectName("datos_raw")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.empezar_boton.setText(_translate("MainWindow", "EMPEZAR"))
        self.terminar_boton.setText(_translate("MainWindow", "TERMINAR (EXPORTACIÓN DE DATOS)"))