# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(419, 377)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Activar = QtWidgets.QPushButton(self.centralwidget)
        self.Activar.setGeometry(QtCore.QRect(210, 20, 141, 101))
        self.Activar.setObjectName("Activar")
        self.desactivar = QtWidgets.QPushButton(self.centralwidget)
        self.desactivar.setGeometry(QtCore.QRect(40, 30, 141, 101))
        self.desactivar.setAcceptDrops(False)
        self.desactivar.setObjectName("desactivar")
        self.etiqueta = QtWidgets.QLabel(self.centralwidget)
        self.etiqueta.setGeometry(QtCore.QRect(90, 180, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.etiqueta.setFont(font)
        self.etiqueta.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.etiqueta.setMouseTracking(False)
        self.etiqueta.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.etiqueta.setAutoFillBackground(True)
        self.etiqueta.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.etiqueta.setObjectName("etiqueta")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Activar.setText(_translate("MainWindow", "Activar"))
        self.desactivar.setText(_translate("MainWindow", "Desactivar"))
        self.etiqueta.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
