# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 606)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Activar = QtWidgets.QPushButton(self.centralwidget)
        self.Activar.setGeometry(QtCore.QRect(700, 520, 121, 51))
        self.Activar.setObjectName("Activar")
        self.desactivar = QtWidgets.QPushButton(self.centralwidget)
        self.desactivar.setGeometry(QtCore.QRect(570, 520, 121, 51))
        self.desactivar.setAcceptDrops(False)
        self.desactivar.setObjectName("desactivar")
        self.temp = QtWidgets.QLabel(self.centralwidget)
        self.temp.setGeometry(QtCore.QRect(440, 20, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.temp.setFont(font)
        self.temp.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.temp.setMouseTracking(False)
        self.temp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.temp.setAutoFillBackground(True)
        self.temp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.temp.setObjectName("temp")
        self.radiacion = QtWidgets.QLabel(self.centralwidget)
        self.radiacion.setGeometry(QtCore.QRect(370, 20, 47, 13))
        self.radiacion.setObjectName("radiacion")
        self.presion = QtWidgets.QLabel(self.centralwidget)
        self.presion.setGeometry(QtCore.QRect(310, 20, 47, 13))
        self.presion.setObjectName("presion")
        self.MplWidget = QtWidgets.QWidget(self.centralwidget)
        self.MplWidget.setGeometry(QtCore.QRect(140, 90, 461, 401))
        self.MplWidget.setObjectName("MplWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Activar.setText(_translate("MainWindow", "Activar"))
        self.desactivar.setText(_translate("MainWindow", "Desactivar"))
        self.temp.setText(_translate("MainWindow", "TextLabel"))
        self.radiacion.setText(_translate("MainWindow", "TextLabel"))
        self.presion.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
